[package]
name = "rust_ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version = "2.0.32", features = ["full", "extra-traits"]}
syn-serde = { version = "0.3", features = ["json"] }